import "unknwn.idl";
interface IMediaSample;

typedef LONGLONG REFERENCE_TIME;

typedef struct _AMMediaType
{
	GUID majortype;
	GUID subtype;
	BOOL bFixedSizeSamples;
	BOOL bTemporalCompression;
	ULONG lSampleSize;
	GUID formattype;
	IUnknown *pUnk;
	ULONG cbFormat;
	BYTE *pbFormat;
} 	AM_MEDIA_TYPE;

typedef HRESULT (*NGCALLBACK);

[
	object,
	uuid(4549d97d-e8ef-4fb4-896e-2f7f867eca2f),
	helpstring("INullGrabber interface controls the behaviour of the Null Grabber Renderer filter."),
]
interface INullGrabber : IUnknown
{
	HRESULT SetAcceptedMediaType([in] const AM_MEDIA_TYPE *pType);
	HRESULT GetConnectedMediaType([out] AM_MEDIA_TYPE *pType);
	HRESULT SetCallback([in] NGCALLBACK Callback);
};